export const SIGNUP_USERS_REQ = 'SIGNUP_USERS_REQ';
export const SIGNUP_USERS_SUC = 'SIGNUP_USERS_SUC';
export const SIGNUP_USERS_FAI = 'SIGNUP_USERS_FAI';

export const GET_USERS_REQ = 'GET_USERS_REQ';
export const GET_USERS_SUC = 'GET_USERS_SUC';
export const GET_USERS_FAI = 'GET_USERS_FAI';

export const LOGIN_USERS_REQ = 'LOGIN_USERS_REQ';
export const LOGIN_USERS_SUC = 'LOGIN_USERS_SUC';
export const LOGIN_USERS_FAI = 'LOGIN_USERS_FAI';
